FROM node:latest
WORKDIR /app
COPY package.json .
RUN npm install
RUN npm audit fix
COPY . .
ENV PORT 4000
ENV APIURL http://piscineapp.zbeb.eu/api/v1/
ENV ISPROD true
RUN npm run build
EXPOSE $PORT
CMD ["node", "server.js"]