version: "3"
services:
    node-frontend:
        build:
            context: ./frontend/
            dockerfile: Dockerfile.prod
            args: 
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        env_file:
            - ./frontend/prodfrontend.env
        command: node server.js
        networks:
            default:
                aliases:
                - node-frontend
    node-backend:
        build:
            context: ./backend/
            args: 
                NODE_ENV: production
        environment:
            - NODE_ENV=production
        env_file:
            - ./backend/backend.env
        command: npm start
        networks:
            default:
                aliases:
                - node-backend
    mongo:
        volumes:
            - ./initdb/:/initdb/:ro
    nginx:
        ports:
            - "80:80"